### ISSUE TITLE
Couldn't replicate the animation

### ISSUE THREAD

**Issue by DanRioDev** [ThatGuySam/expo-router-transition-demo#1]
Hello there, 

thanks for the demo repo, yet, after cloning and running `npm install` then `expo start` , I couldn't see the effect over Expo Go.

Expo installed version: 51.0.25
Router installed version: 3.5.21

The parallax does work.
iOS: 18.0
iPhone 14 Pro Max
Expo client version: 1017616
Supported SDKs: 51

```
The following packages should be updated for best compatibility with the installed expo version:
  expo@51.0.25 - expected version: ~51.0.31
  expo-router@3.5.21 - expected version: ~3.5.23
  jest-expo@51.0.3 - expected version: ~51.0.4
```

https://github.com/user-attachments/assets/a230243c-f9d8-44a7-bad6-16f56b7c29bb

**Comment by ThatGuySam** [comment]
Yeah, it doesn't work. 

This was a demo I made to show how it works but I could get it work either so I left it up in case someone wanted to try and figure it out. 

https://github.com/expo/router/discussions/150#discussioncomment-10398833
